name: Deploy FastAPI App

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy Application
        run: |
          echo "Starting Deployment..."
          # Your deployment command (modify as needed)
          # Example: Restart service, pull latest changes, etc.
          ssh user@your-server-ip 'cd /path/to/app && git pull origin main && systemctl restart fastapi-app'
