name: Book API CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set Up SSH Key
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}  # Base64-encoded private key
          HOST: ec2-13-60-202-106.eu-north-1.compute.amazonaws.com
          USER: ubuntu
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_SSH_KEY" | base64 --decode > ~/.ssh/ec2_ssh_key.pem
          chmod 600 ~/.ssh/ec2_ssh_key.pem
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

      - name: Deploy to AWS EC2
        env:
          HOST: ec2-13-60-202-106.eu-north-1.compute.amazonaws.com
          USER: ubuntu
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2_ssh_key.pem $USER@$HOST <<'EOF'
            cd fastapi-book-project
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart fastapi-book.service
          EOF
