name: Deploy FastAPI to EC2

on:
  push:
    branches:
      - main  # Triggers on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Run Tests
      run: |
        pip install -r requirements.txt
        pytest

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}   # Base64-encoded PEM key
        HOST: ec2-13-60-202-106.eu-north-1.compute.amazonaws.com  # or use your public IP
        USER: ec2-user
      run: |
        # Decode the Base64-encoded private key and save it as a file
        echo "$PRIVATE_KEY" | base64 --decode > my-ec2-key.pem
        chmod 400 my-ec2-key.pem

        # SSH into the EC2 instance and run deployment commands
        ssh -o StrictHostKeyChecking=no -i "my-ec2-key.pem" $USER@$HOST << 'EOF'
          # Ensure necessary packages are installed (Git and Python3)
          if ! command -v git >/dev/null 2>&1; then
            sudo yum install git -y
          fi
          if ! command -v python3 >/dev/null 2>&1; then
            sudo yum install python3 -y
          fi

          # Clone the repository if the project directory doesn't exist
          if [ ! -d "/home/$USER/fastapi-book-project" ]; then
            git clone https://github.com/Cashie11/fastapi-book-project.git /home/$USER/fastapi-book-project
          fi

          # Change to the project directory and pull the latest changes
          cd /home/$USER/fastapi-book-project
          git pull origin main

          # Set up the Python virtual environment if it doesn't already exist
          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi
          source venv/bin/activate

          # Upgrade pip and install dependencies
          pip install --upgrade pip
          pip install -r requirements.txt

          # Restart the FastAPI and Nginx services
          sudo systemctl restart fastapi || echo "fastapi.service not found"
          sudo systemctl restart nginx || echo "nginx.service not found"
        EOF
